# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=questions.models.upload_expected_output_file_location)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
