# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import grader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(upload_to=grader.models.upload_solution_file_location)),
                ('result', models.CharField(blank=True, choices=[('ac', 'AC'), ('wa', 'WA'), ('tle', 'TLE'), ('cte', 'CTE'), ('sigabrt', 'SIGABRT')], max_length=10, null=True)),
                ('email', models.EmailField(max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
