# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_solution_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='solution',
            new_name='file',
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(default='c', max_length=10),
            preserve_default=False,
        ),
    ]
