# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_auto_20180304_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-score', 'timestamp']},
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
    ]
